baseurl = "http://x3phyr.xyz"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "X3PHYR"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

#[[menu.main]]
#name = "Categories"
#url = "/categories/"
#weight = 1
#[[menu.main]]
#name = "Tags"
#url = "/tags/"
#weight = 2
#[[menu.feed]]
#name = "Subscribe"
#url = "/index.xml"

[params]
custom_css = ["css/theme-override.css"]
footer = "[Github](https://github.com/x3phyr-online)"
